# Authored with the in-game dungeon editor.
# # solid, . floor, A arch, L torch, S spawn, C anchor, X exit

[dungeon]
cell_size = 4.0
wall_height = 3.0
rows = [
    "###############################",
    "###############################",
    "######....######......#########",
    "######....######......#########",
    "######....######......#########",
    "######....######......AA.....##",
    "######....######......##.....##",
    "######..S.A....A......##.....##",
    "######L...######L.....##....L##",
    "######....######A##############",
    "######....######.##############",
    "######....######A##############",
    "########A######L..########L..##",
    "########.######...########...##",
    "#####L...######...A......A...##",
    "#####....######...########...##",
    "#####....######...########...##",
    "#####...########A##############",
    "#####...########A##############",
    "######A#########...###.....L.##",
    "######A#########L..###.......##",
    "#####.......####...###.......##",
    "#####L......####...###...X...##",
    "#####.......####...###.......##",
    "#####.......####...A.A...C...##",
    "#####.......####...###.......##",
    "#####.......####...###.......##",
    "################...###.......##",
    "######################.......##",
    "###############################",
    "###############################",
]

[dungeon.light]
colour_srgb = [1.0, 0.68, 0.34]
energy = 4.4
range = 6.5
y = 1.9
