#include <eng/content/PackManifest.h>

#include <algorithm>
#include <fstream>
#include <sstream>
#include <system_error>

#define TOML_EXCEPTIONS 0
#include <tomlplusplus/toml.hpp>

namespace fs = std::filesystem;

namespace eng::content {
namespace {

constexpr int kManifestSchema = 1;

std::string quote(std::string_view text)
{
    std::string out = "\"";
    for (char c : text) {
        if (c == '"' || c == '\\')
            out += '\\';
        out += c;
    }
    out += '"';
    return out;
}

} // namespace

void PackManifest::setDirectory(fs::path directory)
{
    mDirectory = std::move(directory);
}

void PackManifest::add(PackEntry entry)
{
    mEntries.push_back(std::move(entry));
    const size_t index = mEntries.size() - 1;
    mBySource.emplace(mEntries[index].source, index);
    mByGuid.emplace(mEntries[index].guid, index);
}

void PackManifest::set(PackEntry entry)
{
    const auto it = mBySource.find(entry.source);
    if (it == mBySource.end()) {
        add(std::move(entry));
        return;
    }
    const size_t index = it->second;
    // The guid can legitimately change -- a sidecar was stamped, or edited to
    // adopt an id from another branch -- so the guid index has to move with it.
    mByGuid.erase(mEntries[index].guid);
    mEntries[index] = std::move(entry);
    mByGuid.emplace(mEntries[index].guid, index);
}

void PackManifest::clear()
{
    mEntries.clear();
    mBySource.clear();
    mByGuid.clear();
}

void PackManifest::reindex()
{
    mBySource.clear();
    mByGuid.clear();
    for (size_t i = 0; i < mEntries.size(); ++i) {
        mBySource.emplace(mEntries[i].source, i);
        mByGuid.emplace(mEntries[i].guid, i);
    }
}

const PackEntry* PackManifest::bySource(std::string_view logical) const
{
    const auto it = mBySource.find(logical);
    return it == mBySource.end() ? nullptr : &mEntries[it->second];
}

const PackEntry* PackManifest::byGuid(Hash guid) const
{
    const auto it = mByGuid.find(guid);
    return it == mByGuid.end() ? nullptr : &mEntries[it->second];
}

fs::path PackManifest::resolve(std::string_view logical) const
{
    const PackEntry* entry = bySource(logical);
    if (!entry || mDirectory.empty())
        return {};
    return mDirectory / fs::path(entry->output);
}

bool PackManifest::save(const fs::path& directory, std::string& error) const
{
    std::error_code ec;
    fs::create_directories(directory, ec);
    if (ec) {
        error = "cannot create " + directory.string() + ": " + ec.message();
        return false;
    }

    std::ostringstream out;
    out << "# Asset Conditioning Pipeline output index. Generated by raven_acp;\n"
           "# do not hand edit. Delete the directory to force a full rebuild.\n";
    out << "schema = " << kManifestSchema << "\n\n";

    // Sorted by source. The manifest is a build output, and a build output that
    // reorders between runs cannot be diffed to answer "what did this change?".
    std::vector<const PackEntry*> sorted;
    sorted.reserve(mEntries.size());
    for (const PackEntry& entry : mEntries)
        sorted.push_back(&entry);
    std::sort(sorted.begin(), sorted.end(),
              [](const PackEntry* a, const PackEntry* b) {
                  return a->source < b->source;
              });

    for (const PackEntry* entry : sorted) {
        out << "[[asset]]\n";
        out << "guid = " << quote(hashToHex(entry->guid)) << '\n';
        out << "type = " << quote(assetTypeName(entry->type)) << '\n';
        out << "source = " << quote(entry->source) << '\n';
        out << "output = " << quote(entry->output) << '\n';
        out << "build_key = " << quote(hashToHex(entry->buildKey)) << '\n';
        out << "bytes = " << entry->outputBytes << '\n';
        if (!entry->dependencies.empty()) {
            // Sorted: the manifest is diffed to answer "what changed", and a
            // list whose order follows Assimp's material iteration is noise.
            std::vector<std::string> sorted = entry->dependencies;
            std::sort(sorted.begin(), sorted.end());
            out << "depends = [";
            for (size_t i = 0; i < sorted.size(); ++i) {
                if (i)
                    out << ", ";
                out << quote(sorted[i]);
            }
            out << "]\n";
        }
        out << '\n';
    }

    const fs::path path = directory / kPackManifestName;
    const fs::path temp = fs::path(path).concat(".tmp");
    {
        std::ofstream file(temp, std::ios::binary | std::ios::trunc);
        if (!file) {
            error = "cannot open " + temp.string() + " for writing";
            return false;
        }
        file << out.str();
        if (!file) {
            error = "write to " + temp.string() + " failed";
            return false;
        }
    }
    fs::rename(temp, path, ec);
    if (ec) {
        std::error_code ignored;
        fs::remove(temp, ignored);
        error = "cannot replace " + path.string() + ": " + ec.message();
        return false;
    }
    return true;
}

bool PackManifest::load(const fs::path& directory, std::string& error)
{
    clear();
    mDirectory = directory;

    const fs::path path = directory / kPackManifestName;
    const toml::parse_result parsed = toml::parse_file(path.string());
    if (!parsed) {
        error = std::string(parsed.error().description());
        return false;
    }
    const toml::table& table = parsed.table();
    if (const auto* schema = table["schema"].as_integer()) {
        if (schema->get() != kManifestSchema) {
            error = "unsupported manifest schema " +
                    std::to_string(schema->get());
            return false;
        }
    }

    const toml::array* assets = table["asset"].as_array();
    if (!assets)
        return true; // an empty pack is a pack

    for (const toml::node& node : *assets) {
        const toml::table* row = node.as_table();
        if (!row)
            continue;
        PackEntry entry;
        if (const auto* guid = (*row)["guid"].as_string())
            hashFromHex(guid->get(), entry.guid);
        if (const auto* type = (*row)["type"].as_string())
            entry.type = assetTypeFromName(type->get());
        if (const auto* source = (*row)["source"].as_string())
            entry.source = source->get();
        if (const auto* output = (*row)["output"].as_string())
            entry.output = output->get();
        if (const auto* key = (*row)["build_key"].as_string())
            hashFromHex(key->get(), entry.buildKey);
        if (const auto* bytes = (*row)["bytes"].as_integer())
            entry.outputBytes = static_cast<uint64_t>(bytes->get());
        if (const auto* depends = (*row)["depends"].as_array())
            for (const toml::node& dependency : *depends)
                if (const auto* text = dependency.as_string())
                    entry.dependencies.push_back(text->get());
        if (entry.source.empty() || entry.output.empty())
            continue;
        mEntries.push_back(std::move(entry));
    }
    reindex();
    return true;
}

} // namespace eng::content
