#include <editor/assets/ModelImportPipeline.h>

#include <editor/assets/FileBrowser.h>

#include <eng/assets/AssetName.h>

#include <render/AssimpLoader.h>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <limits>
#include <sstream>
#include <system_error>
#include <unordered_map>

namespace ed {
namespace {

namespace fs = std::filesystem;

std::string slugOf(std::string value)
{
    std::string out = eng::assets::canonicalToken(value);
    return out.empty() ? std::string("model") : out;
}

struct Bounds {
    glm::vec3 min{std::numeric_limits<float>::infinity()};
    glm::vec3 max{-std::numeric_limits<float>::infinity()};

    void add(const glm::vec3& point)
    {
        min = glm::min(min, point);
        max = glm::max(max, point);
    }
    bool valid() const { return min.x <= max.x; }
    // The engine's canonical placement pivot: on the ground, centred
    // horizontally. Matching it here is what keeps an imported prop standing on
    // the floor rather than half-sunk into it.
    glm::vec3 bottomCentre() const
    {
        return {(min.x + max.x) * 0.5f, min.y, (min.z + max.z) * 0.5f};
    }
};

Bounds boundsOf(const eng::detail::ImportedModelSubmesh& submesh)
{
    Bounds bounds;
    for (const auto& vertex : submesh.vertices)
        bounds.add(vertex.position);
    return bounds;
}

// True when the mesh actually carries colour. Assimp defaults every vertex to
// opaque white, and picking the vertex-colour material for a model that has
// none renders it flat white instead of showing its texture slot.
bool hasVertexColours(const eng::detail::ImportedModelSubmesh& submesh)
{
    for (const auto& vertex : submesh.vertices) {
        const glm::vec4& c = vertex.colour;
        if (c.r < 0.999f || c.g < 0.999f || c.b < 0.999f)
            return true;
    }
    return false;
}

bool writeObj(const fs::path& path,
              const eng::detail::ImportedModelSubmesh& submesh,
              const glm::vec3& pivot, std::string& error)
{
    std::ofstream stream(path);
    if (!stream) {
        error = "cannot write " + path.string();
        return false;
    }
    stream << "# generated by the editor's model importer\n";
    stream << std::fixed;
    stream.precision(6);
    for (const auto& vertex : submesh.vertices) {
        const glm::vec3 p = vertex.position - pivot;
        stream << "v " << p.x << ' ' << p.y << ' ' << p.z << ' '
               << vertex.colour.r << ' ' << vertex.colour.g << ' '
               << vertex.colour.b << ' ' << vertex.colour.a << '\n';
    }
    // V is written flipped because this renderer's OBJ path flips it again on
    // load (see ModelImport.h). Two flips is the identity; one is a texture
    // upside down, which is the classic symptom of touching only one side.
    for (const auto& vertex : submesh.vertices)
        stream << "vt " << vertex.texcoord.x << ' ' << 1.0f - vertex.texcoord.y
               << '\n';
    for (const auto& vertex : submesh.vertices)
        stream << "vn " << vertex.normal.x << ' ' << vertex.normal.y << ' '
               << vertex.normal.z << '\n';
    for (std::size_t i = 0; i + 2 < submesh.indices.size(); i += 3) {
        const uint32_t a = submesh.indices[i] + 1;
        const uint32_t b = submesh.indices[i + 1] + 1;
        const uint32_t c = submesh.indices[i + 2] + 1;
        stream << "f " << a << '/' << a << '/' << a << ' ' << b << '/' << b
               << '/' << b << ' ' << c << '/' << c << '/' << c << '\n';
    }
    return bool(stream);
}

// Every loadable image under a model's directory, indexed by how a material
// might name it.
//
// Built once per import rather than scanned per material: a model with twenty
// textured submeshes would otherwise walk the same tree twenty times.
//
// Two indices, because exporters get this wrong in two distinct ways. `byName`
// answers "a file called diffuse.png exists somewhere below here", which covers
// the very common pack layout where the model sits in source/ and its textures
// in a sibling folder. `byStem` answers "something called diffuse exists, in
// some format", which covers the equally common case of an .mtl referencing
// diffuse.tga when what actually shipped is diffuse.png.
struct TextureIndex {
    std::unordered_map<std::string, fs::path> byName;
    std::unordered_map<std::string, fs::path> byStem;
};

std::string lowered(std::string value)
{
    std::transform(value.begin(), value.end(), value.begin(),
                   [](unsigned char c) { return char(std::tolower(c)); });
    return value;
}

void indexInto(TextureIndex& index, const fs::path& root)
{
    std::error_code ec;
    if (!fs::is_directory(root, ec))
        return;
    // Bounded: pointing an import at a model inside a very large tree must not
    // hang the editor. findFiles already caps depth and count.
    ScanLimits limits;
    limits.maxFiles = 2000;
    limits.maxDepth = 6;
    for (const FileEntry& entry :
         findFiles(root.string(), textureExtensions(), limits).files) {
        const fs::path path(entry.path);
        // First match wins, and findFiles sorts by label, so which file a name
        // resolves to does not depend on directory iteration order.
        index.byName.emplace(lowered(path.filename().string()), path);
        index.byStem.emplace(lowered(path.stem().string()), path);
    }
}

TextureIndex indexTextures(const fs::path& modelDir)
{
    TextureIndex index;
    indexInto(index, modelDir);
    // Then the parent, whose own entries only fill gaps -- emplace keeps the
    // first. A texture beside the model always beats one belonging to a sibling
    // model that happened to pick the same file name.
    const fs::path parent = modelDir.parent_path();
    if (!parent.empty() && parent != modelDir)
        indexInto(index, parent);
    return index;
}

// Where a material's texture actually lives on disk.
//
// Assimp reports it as the source file spells it, which for the .mtl beside an
// OBJ is a bare "386.png" relative to the model -- not to the editor's working
// directory, which is what makes the naive open() fail. Embedded textures
// ("*0") have no file at all and are refused here rather than half-handled.
//
// The exact paths are tried first and the index only as a fallback, so a model
// that names its textures correctly is never at the mercy of a same-named file
// somewhere else in the tree.
fs::path resolveTexture(const fs::path& modelDir, const std::string& authored,
                        const TextureIndex& index)
{
    if (authored.empty() || authored.front() == '*')
        return {};
    const fs::path candidate(authored);
    std::error_code ec;
    if (candidate.is_absolute() && fs::is_regular_file(candidate, ec))
        return candidate;
    const fs::path direct = modelDir / candidate;
    if (fs::is_regular_file(direct, ec))
        return direct;
    const fs::path beside = modelDir / candidate.filename();
    if (fs::is_regular_file(beside, ec))
        return beside;

    // Filed somewhere else under the model: "textures/wall.png" named as
    // "wall.png", or a stale absolute path whose file name still holds.
    const auto byName = index.byName.find(lowered(candidate.filename().string()));
    if (byName != index.byName.end())
        return byName->second;

    // Same name, different format. Only reached when nothing matched exactly.
    const auto byStem = index.byStem.find(lowered(candidate.stem().string()));
    if (byStem != index.byStem.end())
        return byStem->second;
    return {};
}

// One PSX-look material per texture. Nearest filtering and wrap addressing are
// this project's look, not a default -- a bilinear-filtered 64x64 texture is
// exactly the wrong result here.
std::string materialBlock(const std::string& name, const std::string& texture)
{
    std::ostringstream out;
    out << "[material.\"" << name << "\"]\n"
        << "shader = \"lit\"\n"
        << "texture = \"" << texture << "\"\n"
        << "filter = \"nearest\"\n"
        << "address = \"repeat\"\n\n";
    return out.str();
}

// Replaces this model's marked block in kit.toml, or appends one. Marked rather
// than appended blindly so reimporting a model after fixing it in Blender
// replaces its pieces instead of leaving a second dead copy behind.
bool rewriteCatalogBlock(const fs::path& kitToml, const std::string& slug,
                         const std::string& block, std::string& error)
{
    std::string text;
    {
        std::ifstream input(kitToml);
        if (!input) {
            error = "cannot read " + kitToml.string();
            return false;
        }
        std::ostringstream buffer;
        buffer << input.rdbuf();
        text = buffer.str();
    }

    const std::string begin = "# BEGIN editor import: " + slug;
    const std::string end = "# END editor import: " + slug;
    const std::size_t from = text.find(begin);
    if (from != std::string::npos) {
        const std::size_t to = text.find(end, from);
        if (to != std::string::npos)
            text.erase(from, to + end.size() - from);
        else
            text.erase(from);
    }
    while (!text.empty() && (text.back() == '\n' || text.back() == ' '))
        text.pop_back();
    text += "\n\n" + begin + "\n" + block + end + "\n";

    std::ofstream output(kitToml);
    if (!output) {
        error = "cannot write " + kitToml.string();
        return false;
    }
    output << text;
    return bool(output);
}

} // namespace

std::string modelSlug(const std::string& sourcePath)
{
    return slugOf(fs::path(sourcePath).stem().string());
}

const std::vector<std::string>& textureExtensions()
{
    // Exactly what stb_image decodes -- the renderer loads every texture
    // through stbi_load (engine/src/render/rhi/Image.cpp) and has no other
    // decoder. .dds used to be here because OgreMain carried its own DDS
    // codec; that went with OGRE, so listing it now would promise a format
    // the renderer silently fails to load.
    static const std::vector<std::string> kExtensions = {
        ".png", ".jpg", ".jpeg", ".bmp", ".tga", ".psd",
        ".gif", ".hdr", ".pic",  ".pnm", ".ppm", ".pgm",
    };
    return kExtensions;
}

ModelImportResult importModelToKit(const std::string& sourcePath,
                                   const std::string& assetRoot)
{
    ModelImportResult result;

    const fs::path source = fs::absolute(sourcePath);
    std::error_code ec;
    if (!fs::is_regular_file(source, ec)) {
        result.error = "no such file: " + source.string();
        return result;
    }
    if (!eng::detail::assimpSupportsModelFile(source)) {
        result.error = "this build of Assimp cannot read " +
                       source.extension().string() + " files";
        return result;
    }

    // Source pivot: the parts are pivoted individually below, and their offsets
    // are what reassembles the model. Letting the importer centre it first
    // would fold the arrangement into the geometry and lose it.
    eng::ModelImportOptions options;
    options.pivot = eng::PivotMode::Source;

    eng::detail::ImportedModelData model;
    eng::ModelImportReport report;
    if (!eng::detail::importStaticModel(source, options, model, report)) {
        result.error = report.error.empty()
                           ? ("cannot import " + source.filename().string())
                           : report.error;
        return result;
    }
    if (model.submeshes.empty()) {
        result.error = source.filename().string() + " has no geometry";
        return result;
    }
    result.warnings = report.warnings;

    const std::string slug = modelSlug(sourcePath);
    const std::string prefix = "import_" + slug;

    const fs::path meshDir = fs::path(assetRoot) / "meshes" / "props";
    const fs::path materialDir = fs::path(assetRoot) / "materials";
    const fs::path textureDir = fs::path(assetRoot) / "textures";
    fs::create_directories(meshDir, ec);
    fs::create_directories(materialDir, ec);
    fs::create_directories(textureDir, ec);
    if (ec) {
        result.error = "cannot create import directories: " + ec.message();
        return result;
    }
    const fs::path modelDir = source.parent_path();
    // One walk for the whole import, not one per textured submesh.
    const TextureIndex textures = indexTextures(modelDir);

    Bounds modelBounds;
    for (const auto& submesh : model.submeshes)
        for (const auto& vertex : submesh.vertices)
            modelBounds.add(vertex.position);
    if (!modelBounds.valid()) {
        result.error = source.filename().string() + " has no vertices";
        return result;
    }
    const glm::vec3 modelPivot = modelBounds.bottomCentre();

    std::ostringstream block;
    block << std::fixed;
    block.precision(4);
    std::ostringstream materials;
    // Copied once per distinct source texture: two submeshes sharing a material
    // must not race to write the same file twice.
    std::vector<std::pair<std::string, std::string>> copiedTextures;

    for (std::size_t index = 0; index < model.submeshes.size(); ++index) {
        const eng::detail::ImportedModelSubmesh& submesh =
            model.submeshes[index];
        if (submesh.vertices.empty() || submesh.indices.empty())
            continue;

        const std::string partId =
            model.submeshes.size() == 1
                ? prefix
                : prefix + "_p" + std::to_string(index);
        const std::string objName = partId + ".obj";

        const Bounds partBounds = boundsOf(submesh);
        const glm::vec3 partPivot = partBounds.bottomCentre();
        const glm::vec3 size = partBounds.max - partBounds.min;

        std::string error;
        if (!writeObj(meshDir / objName, submesh, partPivot, error)) {
            result.error = error;
            return result;
        }

        // A texture beside the model gets copied in and given its own material.
        // Failing that, vertex colours if the mesh has them, and the prototype
        // surface if it has neither -- which reads as obviously unfinished
        // rather than as a black prop.
        std::string material = hasVertexColours(submesh)
                                   ? "Game/PropVertexColour"
                                   : "Engine/Psx/PrototypeSurface";
        if (!submesh.sourceTexture.empty()) {
            std::string copiedName;
            for (const auto& [authored, name] : copiedTextures)
                if (authored == submesh.sourceTexture)
                    copiedName = name;

            if (copiedName.empty()) {
                const fs::path found =
                    resolveTexture(modelDir, submesh.sourceTexture, textures);
                if (found.empty()) {
                    result.warnings.push_back(
                        "texture not found under " +
                        modelDir.filename().string() + " or its parent: " +
                        submesh.sourceTexture);
                }
                else {
                    // Prefixed with the model's slug: two models are entitled
                    // to ship a texture called "386.png", and the pack is flat.
                    copiedName = prefix + "_" + found.filename().string();
                    fs::copy_file(found, textureDir / copiedName,
                                  fs::copy_options::overwrite_existing, ec);
                    if (ec) {
                        result.warnings.push_back("could not copy " +
                                                  found.filename().string() +
                                                  ": " + ec.message());
                        ec.clear();
                        copiedName.clear();
                    }
                    else {
                        copiedTextures.emplace_back(submesh.sourceTexture,
                                                    copiedName);
                        result.textures.push_back(copiedName);
                    }
                }
            }
            if (!copiedName.empty()) {
                material = "Game/" + prefix + "/part" + std::to_string(index);
                materials << materialBlock(material, copiedName);
            }
        }

        block << "[[piece]]\n"
              << "id = \"" << partId << "\"\n"
              << "role = \""
              << (model.submeshes.size() == 1 ? "imported_model"
                                              : "imported_part")
              << "\"\n"
              << "mesh = \"meshes/props/" << objName << "\"\n"
              << "material = \"" << material << "\"\n"
              << "socket = \"prop\"\n"
              << "import_scale = 1.0\n"
              << "size = [" << size.x << ", " << size.y << ", " << size.z
              << "]\n\n";

        result.parts.push_back(
            {"kit." + partId, submesh.name, partPivot - modelPivot});
    }

    if (result.parts.empty()) {
        result.error = source.filename().string() + " has no usable submeshes";
        return result;
    }

    // The model itself, as one placeable.
    //
    // A part is a piece; the model is the group of them, and without it the
    // only trace of "these twenty-four objs are one boss" was the scene it was
    // first imported into. The group carries no mesh -- its geometry is its
    // attachments, at the offsets computed above -- and the editor unpacks
    // those into real child entities when it places one, which is what puts
    // the parts in the hierarchy where they can be moved.
    if (result.parts.size() == 1) {
        result.root = result.parts.front().prefab;
    }
    else {
        result.root = "kit." + prefix;
        const glm::vec3 modelSize = modelBounds.max - modelBounds.min;
        block << "[[piece]]\n"
              << "id = \"" << prefix << "\"\n"
              << "role = \"imported_model\"\n"
              << "socket = \"prop\"\n"
              << "import_scale = 1.0\n"
              << "size = [" << modelSize.x << ", " << modelSize.y << ", "
              << modelSize.z << "]\n"
              << "attachments = [\n";
        for (const ImportedPart& part : result.parts) {
            block << "  { prefab = \"" << part.prefab << "\", position = ["
                  << part.offset.x << ", " << part.offset.y << ", "
                  << part.offset.z << "] },\n";
        }
        block << "]\n\n";
    }

    if (report.embeddedTextures > 0)
        result.warnings.push_back(
            std::to_string(report.embeddedTextures) +
            " embedded texture(s) were not extracted -- assign a material in "
            "the Material panel");

    std::string error;
    if (materials.tellp() > 0) {
        const fs::path scriptPath = materialDir / (prefix + ".mat");
        std::ofstream script(scriptPath);
        if (!script) {
            result.error = "cannot write " + scriptPath.string();
            return result;
        }
        script << materials.str();
        if (!script) {
            result.error = "failed writing " + scriptPath.string();
            return result;
        }
        result.materialScript = scriptPath.string();
    }

    if (!rewriteCatalogBlock(fs::path(assetRoot) / "config" / "kit.toml", slug,
                             block.str(), error)) {
        result.error = error;
        return result;
    }

    result.ok = true;
    return result;
}

} // namespace ed
