#include <editor/project/ProjectExport.h>

#include <editor/content/KitCatalog.h>
#include <editor/content/SceneCook.h>
#include <editor/content/SceneSource.h>

#include <eng/Log.h>
#include <eng/assets/AssetRoot.h>
#include <eng/runtime/Project.h>

#include <spawn.h>
#include <sys/wait.h>

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <system_error>

extern char** environ;

namespace fs = std::filesystem;

namespace ed {
namespace {

// The project's own directories worth shipping.
//
// `scenes` is here for the .scn sources as well as the cooked maps, which looks
// wasteful and is not: they are small, and a shipped game that still carries
// its scenes can be opened in the editor by whoever received it. That is how a
// modding story starts, and dropping them buys back kilobytes.
//
// Deliberately absent: `.raven`, which is per-user working state -- the cooked
// output is written fresh by the export, not copied from whatever the last
// playtest happened to leave there.
const std::vector<std::string>& projectDirectories()
{
    static const std::vector<std::string> kDirs = {
        "scenes", "scripts", "materials", "textures", "meshes", "config",
        "audio",  "fonts",   "shaders",   "ui",
    };
    return kDirs;
}

std::string executableNameFrom(const std::string& projectName)
{
    std::string name;
    for (const char c : projectName) {
        if (std::isalnum(static_cast<unsigned char>(c)))
            name += char(std::tolower(static_cast<unsigned char>(c)));
        else if (!name.empty() && name.back() != '-')
            name += '-';
    }
    while (!name.empty() && name.back() == '-')
        name.pop_back();
    return name.empty() ? "game" : name;
}

bool directoryIsEmpty(const fs::path& dir)
{
    std::error_code ec;
    if (!fs::exists(dir, ec))
        return true;
    return fs::directory_iterator(dir, ec) == fs::directory_iterator();
}

// Copies a directory tree, counting what it moved. Missing sources are not an
// error: a project with no textures/ is a project that has not needed one, and
// refusing to export it would be absurd.
void copyTree(const fs::path& from, const fs::path& to, ExportReport& report)
{
    std::error_code ec;
    if (!fs::is_directory(from, ec))
        return;
    // Created even when the source is empty. A project's assets.toml declares
    // its resource directories whether or not it has put anything in them yet,
    // and a mounted pack that names a directory which is not there warns on
    // every launch of the shipped game.
    fs::create_directories(to, ec);

    for (fs::recursive_directory_iterator it(from, ec), end; it != end;
         it.increment(ec)) {
        if (ec)
            break;
        const fs::path relative = fs::relative(it->path(), from, ec);
        if (ec)
            continue;
        const fs::path target = to / relative;
        if (it->is_directory()) {
            fs::create_directories(target, ec);
            continue;
        }
        if (!it->is_regular_file())
            continue;
        fs::create_directories(target.parent_path(), ec);
        fs::copy_file(it->path(), target,
                      fs::copy_options::overwrite_existing, ec);
        if (ec)
            continue;
        ++report.filesCopied;
        report.bytesCopied += std::size_t(fs::file_size(it->path(), ec));
    }
}

// The manifest the shipped build reads. Written rather than copied: the source
// tree's assets.toml describes a source tree, and half its resource
// directories will not exist in an export.
bool writeEngineManifest(const fs::path& assetsDir, ExportReport& report)
{
    std::ofstream out(assetsDir / "assets.toml", std::ios::trunc);
    if (!out) {
        report.error = "could not write assets.toml";
        return false;
    }
    out << "# Generated by the exporter. The engine content a shipped game\n"
           "# needs; the project's own pack is mounted over this at startup.\n"
           "schema = 1\n\n"
           "[[pack]]\n"
           "id = \"content\"\n"
           "dir = \".\"\n"
           "resources = [\n";
    // Only the directories that were actually copied, so the renderer does not
    // register a resource location that is not there.
    for (const char* dir :
         {"materials", "shaders", "compositors", "fonts", "ui", "textures",
          "textures/dungeon", "textures/props", "textures/prototype",
          "textures/surfaces", "textures/vfx", "textures/viewmodels",
          "particles/textures", "particles/textures/sheets"}) {
        std::error_code ec;
        if (fs::is_directory(assetsDir / dir, ec))
            out << "    \"" << dir << "\",\n";
    }
    out << "]\n\n[mounts]\ngame = [\"content\"]\neditor = [\"content\"]\n"
           "demo = [\"content\"]\n";
    return bool(out);
}

} // namespace

const std::vector<std::string>& engineRuntimeDirectories()
{
    static const std::vector<std::string> kDirs = {
        // Compiled at startup; a build without them renders nothing.
        "shaders", "compositors",
        // Drawn with: the loading screen, the console, any UI.
        "fonts", "ui",
        // What things wear, and what those materials sample.
        "materials", "textures",
        // The particle library and its atlases.
        "particles",
        // TOML the engine reads by name -- particles.toml above all.
        "config",
    };
    return kDirs;
}

ExportReport exportProject(const ExportOptions& options)
{
    ExportReport report;
    std::error_code ec;

    eng::runtime::Project project;
    if (!eng::runtime::loadProject(options.projectDir, project)) {
        report.error = "not a project: " + options.projectDir;
        return report;
    }

    const fs::path out = fs::absolute(options.outDir);
    if (!options.overwrite && !directoryIsEmpty(out)) {
        // Merging a build into a directory that already has things in it is
        // not recoverable, and the directory somebody types by mistake is
        // usually one with something in it.
        report.error = out.string() +
                       " is not empty; pass --overwrite to write into it anyway";
        return report;
    }
    fs::create_directories(out, ec);
    if (ec) {
        report.error = "could not create " + out.string() + ": " + ec.message();
        return report;
    }

    // --- the engine's content ------------------------------------------
    const fs::path engineRoot =
        options.engineAssets.empty()
            ? eng::assets::packDir("content")
            : fs::path(options.engineAssets);
    if (engineRoot.empty() || !fs::is_directory(engineRoot, ec)) {
        report.error = "no engine content root to export from";
        return report;
    }
    const fs::path assetsOut = out / "assets";
    for (const std::string& dir : engineRuntimeDirectories())
        copyTree(engineRoot / dir, assetsOut / dir, report);
    if (!writeEngineManifest(assetsOut, report))
        return report;

    // --- the project ----------------------------------------------------
    // Under `project/` rather than merged into assets/, so the two packs stay
    // separable: the player mounts the engine's and then overlays this one,
    // which is exactly what it does from the editor.
    const fs::path projectOut = out / "project";
    fs::create_directories(projectOut, ec);
    fs::copy_file(project.dir / "project.toml", projectOut / "project.toml",
                  fs::copy_options::overwrite_existing, ec);
    if (ec) {
        report.error = "could not copy project.toml: " + ec.message();
        return report;
    }
    ++report.filesCopied;
    if (fs::is_regular_file(project.dir / "assets.toml", ec)) {
        fs::copy_file(project.dir / "assets.toml", projectOut / "assets.toml",
                      fs::copy_options::overwrite_existing, ec);
        ++report.filesCopied;
    }
    for (const std::string& dir : projectDirectories())
        copyTree(project.dir / dir, projectOut / dir, report);

    // --- cook every scene ------------------------------------------------
    // Fresh, into the exported tree. Not copied from the project's .raven:
    // that holds whatever the last playtest left, which may be older than the
    // scenes beside it, and shipping a stale map is the kind of bug that only
    // shows up on somebody else's machine.
    game::content::KitCatalog catalog;
    std::string kitError;
    if (const fs::path kit = eng::assets::resolve("config/kit.toml");
        !kit.empty())
        game::content::KitCatalog::load(kit.string(), catalog, kitError);

    const fs::path cookedOut = projectOut / ".raven" / "cooked";
    fs::create_directories(cookedOut, ec);

    std::vector<fs::path> scenes;
    for (fs::recursive_directory_iterator it(project.dir / "scenes", ec), end;
         it != end; it.increment(ec)) {
        if (ec)
            break;
        if (it->is_regular_file() && it->path().extension() == ".scn")
            scenes.push_back(it->path());
    }
    // Sorted, so an export is reproducible and its report reads the same twice.
    std::sort(scenes.begin(), scenes.end());

    for (const fs::path& scene : scenes) {
        const std::string logical =
            fs::relative(scene, project.dir, ec).generic_string();
        game::content::SceneDocument document;
        std::string error;
        if (!game::content::loadSceneSource(scene.string(), document, error)) {
            report.skippedScenes.push_back(logical + ": " + error);
            continue;
        }
        const fs::path map = cookedOut / (scene.stem().string() + ".map");
        if (!game::content::cookToMap(document, catalog, map.string(), error,
                                      project.dir.string())) {
            report.skippedScenes.push_back(logical + ": " + error);
            continue;
        }
        report.cookedScenes.push_back(logical);
        ++report.filesCopied;
        report.bytesCopied += std::size_t(fs::file_size(map, ec));
    }

    if (report.cookedScenes.empty()) {
        // A build with no playable scene in it is not a build. Refusing is
        // kinder than shipping something that opens to a black window.
        report.error = "no scene cooked; the export would not be playable";
        return report;
    }

    // --- the player -------------------------------------------------------
    fs::path player = options.playerPath.empty() ? fs::path{}
                                                 : fs::path(options.playerPath);
    if (player.empty()) {
        // Beside the exporting binary, which is where the build tree puts both.
        player = fs::path(eng::assets::project()) / "build" / "raven_player";
    }
    if (!fs::is_regular_file(player, ec)) {
        report.error = "player binary not found at " + player.string() +
                       "; pass --player";
        return report;
    }

    const std::string exeName = options.executableName.empty()
                                    ? executableNameFrom(project.name)
                                    : options.executableName;
    const fs::path shipped = out / exeName;
    fs::copy_file(player, shipped, fs::copy_options::overwrite_existing, ec);
    if (ec) {
        report.error = "could not copy the player: " + ec.message();
        return report;
    }
    fs::permissions(shipped,
                    fs::perms::owner_all | fs::perms::group_read |
                        fs::perms::group_exec | fs::perms::others_read |
                        fs::perms::others_exec,
                    ec);

    // Strip the debug symbols out of the shipped copy.
    //
    // Not a micro-optimisation: this tree builds RelWithDebInfo by default, and
    // the player carries 200 MB of DWARF into a 15 MB program. Exporting it
    // unstripped made a game whose engine content is 14 MB into a 219 MB
    // download, and the symbols are of no use whatever to somebody who was
    // handed a binary. The build tree's own copy keeps them, which is what the
    // developer debugs against.
    //
    // Best effort: `strip` is not guaranteed to exist, and a build that is
    // large is still a build that runs. `--strip-debug` rather than `--strip-all`
    // so a crash in a shipped game still produces function names in a backtrace.
    if (!options.keepDebugSymbols) {
        std::string command = "strip";
        std::string flag = "--strip-debug";
        std::string file = shipped.string();
        char* argv[] = {command.data(), flag.data(), file.data(), nullptr};
        pid_t pid = 0;
        if (posix_spawnp(&pid, command.c_str(), nullptr, nullptr, argv,
                         environ) == 0) {
            int status = 0;
            waitpid(pid, &status, 0);
        } else {
            eng::log::warn("export: `strip` not found; shipping symbols too");
        }
    }

    ++report.filesCopied;
    report.bytesCopied += std::size_t(fs::file_size(shipped, ec));
    report.executable = shipped.string();

    report.ok = true;
    return report;
}

} // namespace ed
