#!/usr/bin/env python3
"""Rasterise a TTF into a 1-bit pixel-font atlas for eng::ui::BitmapFont.

The runtime never touches a TTF: it loads a PNG grid plus a TOML metrics file,
so the UI font is a shipped asset and text metrics are deterministic across
machines. Re-run this only when the font or its size changes.

    tools/gen_font_atlas.py --font /usr/share/fonts/.../DejaVuSansMono.ttf \
        --size 12 --name ui_regular

Glyphs are thresholded to full alpha, which is what makes an ordinary vector
face read as a pixel font: no anti-aliased fringe survives nearest-neighbour
magnification. Advance widths come from the inked bounds, not the face metrics,
so the result is proportional rather than monospaced.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FIRST = 32
LAST = 126
COLUMNS = 16


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", required=True)
    ap.add_argument("--size", type=int, default=12)
    ap.add_argument("--name", default="ui_regular")
    ap.add_argument("--threshold", type=int, default=128)
    ap.add_argument("--out", default="assets/engine/fonts")
    args = ap.parse_args()

    face = ImageFont.truetype(args.font, args.size)
    ascent, descent = face.getmetrics()
    cell_w = args.size + 4
    cell_h = ascent + descent

    count = LAST - FIRST + 1
    rows = (count + COLUMNS - 1) // COLUMNS
    atlas = Image.new("RGBA", (COLUMNS * cell_w, rows * cell_h), (255, 255, 255, 0))

    advances: list[int] = []
    for index in range(count):
        code = FIRST + index
        cx = (index % COLUMNS) * cell_w
        cy = (index // COLUMNS) * cell_h

        glyph = Image.new("L", (cell_w, cell_h), 0)
        ImageDraw.Draw(glyph).text((1, 0), chr(code), font=face, fill=255)
        # Threshold: a pixel font has no partial coverage.
        glyph = glyph.point(lambda v: 255 if v >= args.threshold else 0)

        box = glyph.getbbox()
        if code == ord(" ") or box is None:
            advances.append(max(3, args.size // 3))
            continue

        # Left-align the ink so kerning is uniform, then advance by ink width.
        left, _, right, _ = box
        shifted = Image.new("L", (cell_w, cell_h), 0)
        shifted.paste(glyph.crop((left, 0, right, cell_h)), (0, 0))
        advances.append(right - left + 1)

        white = Image.new("RGBA", (cell_w, cell_h), (255, 255, 255, 255))
        white.putalpha(shifted)
        atlas.paste(white, (cx, cy))

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    png = out_dir / f"{args.name}.png"
    atlas.save(png)

    toml = out_dir / f"{args.name}.toml"
    lines = [
        "# Generated by tools/gen_font_atlas.py -- do not edit by hand.",
        "[font]",
        f'texture = "{args.name}.png"',
        f"first_codepoint = {FIRST}",
        f"columns = {COLUMNS}",
        f"cell_width = {cell_w}",
        f"cell_height = {cell_h}",
        f"ascent = {ascent}",
        # Lines are packed tighter than the full cell: the cell reserves room
        # for a full descender under every glyph, which reads as a gap in a
        # HUD where most strings are upper case.
        f"line_height = {ascent + (descent + 1) // 2}",
        "advances = [" + ", ".join(str(a) for a in advances) + "]",
        "",
    ]
    toml.write_text("\n".join(lines))
    print(f"{png} ({atlas.width}x{atlas.height}), {toml}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
