#!/usr/bin/env python3
"""One-shot converter: glTF/GLB -> extended OBJ (vertex colors on the `v` line).

Used because the system Ogre 14.5 install has no Codec_Assimp plugin.
Emits one OBJ per glTF *mesh* (node transforms are NOT baked -- the demo
recreates the Godot node hierarchy with Ogre SceneNodes instead).

Extended OBJ: `v x y z r g b a` (vertex color extension), `vt`, `vn`,
faces as `f v/vt/vn`. Parsed by src/ObjLoader.cpp.
"""
import json, struct, base64, sys, os

def load_gltf(path):
    data = open(path, 'rb').read()
    if data[:4] == b'glTF':
        jlen = struct.unpack('<I', data[12:16])[0]
        js = json.loads(data[20:20 + jlen])
        off = 20 + jlen
        clen, = struct.unpack('<I', data[off:off + 4])
        blob = data[off + 8:off + 8 + clen]
    else:
        js = json.loads(data)
        uri = js['buffers'][0]['uri']
        assert uri.startswith('data:'), 'external buffers not supported'
        blob = base64.b64decode(uri.split(',', 1)[1])
    return js, blob

CTYPE = {5120: ('b', 1), 5121: ('B', 1), 5122: ('h', 2), 5123: ('H', 2),
         5125: ('I', 4), 5126: ('f', 4)}
NCOMP = {'SCALAR': 1, 'VEC2': 2, 'VEC3': 3, 'VEC4': 4}

def read_accessor(js, blob, idx):
    acc = js['accessors'][idx]
    bv = js['bufferViews'][acc['bufferView']]
    fmt, sz = CTYPE[acc['componentType']]
    n = NCOMP[acc['type']]
    off = bv.get('byteOffset', 0) + acc.get('byteOffset', 0)
    stride = bv.get('byteStride') or sz * n
    out = []
    for i in range(acc['count']):
        vals = struct.unpack_from('<' + fmt * n, blob, off + i * stride)
        if acc.get('normalized'):
            maxv = float((1 << (sz * 8)) - 1) if fmt.isupper() else float((1 << (sz * 8 - 1)) - 1)
            vals = tuple(v / maxv for v in vals)
        out.append(vals)
    return out

def write_obj(js, blob, mesh_idx, out_path):
    prim = js['meshes'][mesh_idx]['primitives'][0]
    a = prim['attributes']
    pos = read_accessor(js, blob, a['POSITION'])
    nrm = read_accessor(js, blob, a['NORMAL'])
    uv = read_accessor(js, blob, a['TEXCOORD_0'])
    col = read_accessor(js, blob, a['COLOR_0']) if 'COLOR_0' in a else None
    idx = [v[0] for v in read_accessor(js, blob, prim['indices'])]
    with open(out_path, 'w') as f:
        f.write('# generated by gltf_to_obj.py from %s mesh %d (%s)\n' %
                (os.path.basename(sys.argv[1]) if len(sys.argv) > 1 else '?',
                 mesh_idx, js['meshes'][mesh_idx].get('name', '')))
        for i, p in enumerate(pos):
            if col:
                c = col[i]
                f.write('v %.6f %.6f %.6f %.6f %.6f %.6f %.6f\n' % (p + tuple(c[:4])))
            else:
                f.write('v %.6f %.6f %.6f\n' % p)
        for t in uv:
            # ObjLoader flips v (like Godot's OBJ importer, since Blender OBJs are
            # v-up). Pre-flip here so the flip round-trips back to the glTF value.
            f.write('vt %.6f %.6f\n' % (t[0], 1.0 - t[1]))
        for nn in nrm:
            f.write('vn %.6f %.6f %.6f\n' % nn)
        for t in range(0, len(idx), 3):
            i0, i1, i2 = idx[t] + 1, idx[t + 1] + 1, idx[t + 2] + 1
            f.write('f %d/%d/%d %d/%d/%d %d/%d/%d\n' %
                    (i0, i0, i0, i1, i1, i1, i2, i2, i2))
    print('wrote', out_path, len(pos), 'verts', len(idx) // 3, 'tris')

if __name__ == '__main__':
    src, outdir = sys.argv[1], sys.argv[2]
    js, blob = load_gltf(src)
    names = sys.argv[3].split(',') if len(sys.argv) > 3 else \
        [js['meshes'][i].get('name', 'mesh%d' % i) for i in range(len(js['meshes']))]
    for i, name in enumerate(names):
        write_obj(js, blob, i, os.path.join(outdir, name + '.obj'))
