#!/usr/bin/env python3
"""Slice PSX_Modular_Medieval building-block shells into dungeon tiles.

The kit's wall pieces are closed zero-thickness box shells (walls on all
four sides, made to be seen from outside as houses). A dungeon needs a
per-edge vocabulary instead, so this script cuts single wall faces out of
the shells and re-emits them as extended OBJs (same format as
gltf_to_obj.py: `v x y z [r g b a]`, `vt`, `vn`, `f v/vt/vn`).

Produced set (all sized for a 4 m grid cell, 3 m walls):
  tile_floor.obj        stone_floor_4x4, as-is           x[0,4] z[-4,0], y=0
  tile_ceiling.obj      wooden_floor_4x4, mirrored in y  faces point down
  tile_wall.obj         z+ face of stone_square          x[0,4] wall at z=0,
                                                         normal +z
  tile_wall_plaster.obj z+ face of plaster_wall_stone_base (hall variant)
  tile_arch.obj         stone_archway, as-is             tunnel along z
  tile_pillar.obj       wood_support_beam_metal, as-is   3.1 m corner post

Usage: slice_tiles.py <extracted-kit-dir> <out-dir>
where <extracted-kit-dir> contains 'Building blocks/*.glb'.
"""
import os
import sys
import importlib.util

spec = importlib.util.spec_from_file_location(
    'gltf_to_obj', os.path.join(os.path.dirname(__file__), 'gltf_to_obj.py'))
g = importlib.util.module_from_spec(spec)
spec.loader.exec_module(g)


def load_prim(path):
    js, blob = g.load_gltf(path)
    prim = js['meshes'][0]['primitives'][0]
    a = prim['attributes']
    return {
        'pos': g.read_accessor(js, blob, a['POSITION']),
        'nrm': g.read_accessor(js, blob, a['NORMAL']),
        'uv': g.read_accessor(js, blob, a['TEXCOORD_0']),
        'col': g.read_accessor(js, blob, a['COLOR_0']) if 'COLOR_0' in a else None,
        'idx': [v[0] for v in g.read_accessor(js, blob, prim['indices'])],
    }


def filter_zplus(prim):
    """Keep only triangles lying entirely in the z=max plane (one wall)."""
    zmax = max(p[2] for p in prim['pos'])
    idx = prim['idx']
    keep = []
    for t in range(0, len(idx), 3):
        tri = idx[t:t + 3]
        if all(abs(prim['pos'][i][2] - zmax) < 0.05 for i in tri):
            keep.extend(tri)
    return dict(prim, idx=keep)


def subdivide(prim, max_edge):
    """4-split triangles until no edge exceeds max_edge.

    The engine's PSX shaders interpolate UVs affinely (noperspective), so
    large triangles warp visibly near the screen edges up close; dense
    tessellation is the period-correct cure. Midpoints are cached per edge
    so shared edges split identically (no cracks).
    """
    pos = list(prim['pos'])
    uv = list(prim['uv'])
    nrm = list(prim['nrm'])
    col = list(prim['col']) if prim['col'] else None
    mid_cache = {}

    def dist2(a, b):
        return sum((a[i] - b[i]) ** 2 for i in range(3))

    def midpoint(a, b):
        key = (min(a, b), max(a, b))
        if key in mid_cache:
            return mid_cache[key]
        pos.append(tuple((pos[a][i] + pos[b][i]) / 2 for i in range(3)))
        uv.append(tuple((uv[a][i] + uv[b][i]) / 2 for i in range(2)))
        n = tuple((nrm[a][i] + nrm[b][i]) / 2 for i in range(3))
        length = max(sum(c * c for c in n) ** 0.5, 1e-6)
        nrm.append(tuple(c / length for c in n))
        if col is not None:
            col.append(tuple((col[a][i] + col[b][i]) / 2
                             for i in range(len(col[a]))))
        i = len(pos) - 1
        mid_cache[key] = i
        return i

    max2 = max_edge * max_edge
    stack = [tuple(prim['idx'][t:t + 3]) for t in range(0, len(prim['idx']), 3)]
    out = []
    while stack:
        a, b, c = stack.pop()
        if max(dist2(pos[a], pos[b]), dist2(pos[b], pos[c]),
               dist2(pos[c], pos[a])) <= max2:
            out.extend((a, b, c))
            continue
        ab, bc, ca = midpoint(a, b), midpoint(b, c), midpoint(c, a)
        stack.extend(((a, ab, ca), (ab, b, bc), (ca, bc, c), (ab, bc, ca)))
    return {'pos': pos, 'uv': uv, 'nrm': nrm, 'col': col, 'idx': out}


def mirror_y(prim):
    """Mirror in y (for ceilings); reverses winding to keep faces valid."""
    out = dict(prim)
    out['pos'] = [(p[0], -p[1], p[2]) for p in prim['pos']]
    out['nrm'] = [(n[0], -n[1], n[2]) for n in prim['nrm']]
    idx = prim['idx']
    out['idx'] = []
    for t in range(0, len(idx), 3):
        out['idx'].extend((idx[t], idx[t + 2], idx[t + 1]))
    return out


def write_obj(prim, out_path, note):
    # Compact: re-index so only referenced vertices are written.
    used = sorted(set(prim['idx']))
    remap = {old: new for new, old in enumerate(used)}
    with open(out_path, 'w') as f:
        f.write('# generated by slice_tiles.py (%s)\n' % note)
        for i in used:
            p = prim['pos'][i]
            if prim['col']:
                f.write('v %.6f %.6f %.6f %.6f %.6f %.6f %.6f\n' %
                        (tuple(p) + tuple(prim['col'][i][:4])))
            else:
                f.write('v %.6f %.6f %.6f\n' % tuple(p))
        for i in used:
            t = prim['uv'][i]
            f.write('vt %.6f %.6f\n' % (t[0], 1.0 - t[1]))
        for i in used:
            f.write('vn %.6f %.6f %.6f\n' % tuple(prim['nrm'][i]))
        idx = prim['idx']
        for t in range(0, len(idx), 3):
            a, b, c = (remap[idx[t]] + 1, remap[idx[t + 1]] + 1,
                       remap[idx[t + 2]] + 1)
            f.write('f %d/%d/%d %d/%d/%d %d/%d/%d\n' %
                    (a, a, a, b, b, b, c, c, c))
    print('wrote', out_path, len(used), 'verts', len(idx) // 3, 'tris')


def main():
    kit, out = sys.argv[1], sys.argv[2]
    blocks = os.path.join(kit, 'Building blocks')
    os.makedirs(out, exist_ok=True)
    jobs = [
        ('stone_floor_4x4.glb', 'tile_floor.obj', None, 'floor, as-is'),
        ('wooden_floor_4x4.glb', 'tile_ceiling.obj', mirror_y,
         'ceiling, y-mirrored'),
        ('stone_square.glb', 'tile_wall.obj', filter_zplus,
         'z+ face of the shell'),
        ('plaster_wall_stone_base.glb', 'tile_wall_plaster.obj', filter_zplus,
         'z+ face of the shell'),
        ('stone_archway.glb', 'tile_arch.obj', None, 'arch tunnel, as-is'),
        ('wood_support_beam_metal.glb', 'tile_pillar.obj', None,
         'corner post, as-is'),
    ]
    for src, dst, op, note in jobs:
        prim = load_prim(os.path.join(blocks, src))
        if op:
            prim = op(prim)
        # Affine (noperspective) UV warp is tamed by dense tessellation;
        # 0.6 m matches the old interior test box (10 m / subdiv 7).
        prim = subdivide(prim, 0.6)
        write_obj(prim, os.path.join(out, dst), '%s: %s' % (src, note))


if __name__ == '__main__':
    main()
