// The starting scenes, and the promise that they are playable.
//
// Templates matter more than they look: they are the first thing anyone sees in
// the editor, and a template that does not cook hands a new author a broken
// document to debug before they have placed anything.

#include "SceneTemplates.h"
#include "SceneValidate.h"
#include "SceneWriter.h"
#include "TestAssets.h"

#include <cstdlib>
#include <iostream>
#include <string>

using namespace game::content;

static void require(bool condition, const std::string& message)
{
    if (!condition) {
        std::cerr << "SceneTemplateTests: " << message << '\n';
        std::exit(1);
    }
}

int main()
{
    game::test::mountGameAssets();
    KitCatalog catalog;
    std::string error;
    require(KitCatalog::load(game::test::asset("kit.toml"), catalog, error), error);
    const GridConfig grid = GridConfig::fromCatalog(catalog);

    for (const SceneTemplate which :
         {SceneTemplate::Empty, SceneTemplate::Room, SceneTemplate::TechDemo}) {
        const std::string label = sceneTemplateName(which);
        SceneDocument document;
        require(buildTemplate(which, grid, catalog, "scene.test", document, error),
                label + ": " + error);

        // Playable from the first frame: a spawn, an exit, and nothing that
        // blocks the cook.
        int spawns = 0, exits = 0;
        for (const Entity& entity : document.entities) {
            spawns += entity.playerSpawn ? 1 : 0;
            exits += entity.exitYawDegrees ? 1 : 0;
        }
        require(spawns == 1, label + " has exactly one player spawn");
        require(exits == 1, label + " has exactly one exit");

        const std::vector<Issue> issues = validate(document, catalog);
        for (const Issue& issue : issues)
            std::cerr << "  " << label << ": " << severityName(issue.severity)
                      << ' ' << issue.code << " (" << issue.entity << ")\n";
        require(issues.empty(), label + " validates completely clean");

        // Deterministic: the shipped .scn files are generated by this, so a
        // template that varied between runs would make every regeneration a
        // spurious diff.
        SceneDocument again;
        require(buildTemplate(which, grid, catalog, "scene.test", again, error),
                error);
        require(serializeSceneSource(document) == serializeSceneSource(again),
                label + " builds identically every time");
    }

    // The tech demo is the one that has to exercise the whole pipeline, or it
    // is not demonstrating anything.
    {
        SceneDocument demo;
        require(buildTemplate(SceneTemplate::TechDemo, grid, catalog,
                              "scene.tech_demo", demo, error),
                error);
        bool light = false, sun = false, marker = false, enemy = false;
        bool pickup = false, trigger = false, collider = false, override_ = false;
        for (const Entity& entity : demo.entities) {
            if (entity.light)
                (entity.light->type == LightAuthor::Type::Directional ? sun
                                                                      : light) = true;
            marker = marker || entity.marker.has_value();
            enemy = enemy || entity.enemySpawn.has_value();
            pickup = pickup || entity.pickup.has_value();
            trigger = trigger || entity.trigger.has_value();
            collider = collider || entity.collider.has_value();
            override_ = override_ || !entity.material.empty();
        }
        require(light && sun, "both light types appear");
        require(marker, "a marker appears");
        require(enemy, "an enemy spawn appears");
        require(pickup, "a pickup appears");
        require(trigger, "a trigger volume appears");
        require(collider, "a collider appears");
        require(override_, "a per-entity material override appears");
        require(demo.entities.size() > 100,
                "and it is a real level, not a token one");
    }

    std::cout << "SceneTemplateTests: ok\n";
    return 0;
}
